# Mean

Let $X=(x_1,\ldots,x_N)$ and $X=(y_1,\ldots,y_N)$ be data sets

mean is defined as

\begin{equation}
\mu = \frac{\sum x_k }{N}
\end{equation}

variance is defined as

\begin{equation}
var = \sigma^2 = \frac{\sum(x_j - \mu)^2}{N-1}
\end{equation}

where $\sigma$ is standard deviation

covariance is defined as

\begin{equation}
cov = \frac{\sum (x_k-\mu)(y_k-\mu)}{N-1}
\end{equation}
