
# Line equation

Generaal equation

$$ax + by + c = 0$$

Explicit equation

$$y = ax + b$$

Parametric representation
$$L_p=\mathbf{p} + t \mathbf{u}$$

where:

$t$ parameter\
$\mathbf{u}$ collinear vector\
$\mathbf{p}$ some point on line



Normal representation

$$r=x\cos(\theta) + y \sin(\theta)$$

$$L_n=\rho+\theta$$


Conversion from normal to parametric representation

we can choose unit vector (the direction can be any)

$$x_u = - \sin(\theta)$$
$$y_u = \cos(\theta)$$


the starting point can be taken as intersection of normal from the origin and the line

$$x_p = \rho \cos(\theta)$$
$$y_p = \rho \sin(\theta)$$


