\documentclass[12pt]{article}

\usepackage{amsmath,amssymb,amsfonts,textcomp}
\usepackage[parfill]{parskip}
\usepackage[letterpaper,left=2cm,right=2cm,top=2cm,bottom=2cm]{geometry}
\usepackage{hyperref}

\begin{document}


Householder matrix has form


\end{document}
